### PR TITLE
Optional Encryption

### PR DESCRIPTION
**Pull request by steverecio**
Add variables for at-rest and in-transit encryption (defaults to false as encryption requires redis version 3.2.6)

### CODE REVIEW

**Comment by sheax0r** [comment]
@antonbabenko I'd like to see this merged. I'm using my own fork that has this functionality at present, but it'd be nice to switch back to the main version.

**Comment by kpankonen** [comment]
You might want to update the README.md with the new parameters (using https://github.com/segmentio/terraform-docs), and `terraform fmt` to clean up the whitespace in variables.tf

**Comment by ozbillwang** [comment]
@steverecio 

Could you please update your PR as @kpankonen recommended? Hope it can be merged ASAP

cc @antonbabenko

**Comment by steverecio** [comment]
@kpankonen @ozbillwang I've implemented the requested changes using `terraform fmt` and `terraform-docs`. Holler if there's anything missing.

@antonbabenko should be good to merge now

**Comment by antonbabenko** [comment]
[v1.9.0](https://github.com/terraform-community-modules/tf_aws_elasticache_redis/releases/v1.9.0) has been just released with this fix.

**Pull request closed without merging**
