### PR TITLE
fixing outputs

### PR DESCRIPTION
**Pull request by vinay-ux**

### CODE REVIEW

**Comment by antonbabenko** [comment]
What is the reason for this PR? The output seems valid - https://www.terraform.io/docs/providers/aws/r/elasticache_subnet_group.html#subnet_ids-1

**Comment by vinay-ux** [comment]
Yeah, this does seem valid. I was getting this error when i was running a plan
 `Resource 'aws_elasticache_subnet_group.redis_subnet_group' does not have attribute 'subnet_ids' for variable 'aws_elasticache_subnet_group.redis_subnet_group.subnet_ids'`

**Comment by antonbabenko** [comment]
Yes, you are right. I just compared this module with outputs in [VPC module](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/outputs.tf#L123-L131). Thanks for this PR!

**Comment by antonbabenko** [comment]
[v1.2.0](https://github.com/terraform-community-modules/tf_aws_elasticache_redis/releases/v1.2.0) has been released.

**Comment by vinay-ux** [comment]
Thanks :)

**Comment by tfhartmann** [comment]
> 
> v1.2.0 <https://github.com/terraform-community-modules/tf_aws_elasticache_redis/releases/v1.2.0> has been released.
> 
> 

Right on!

**Pull request merged**
